// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asr.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_asr_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_asr_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_asr_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_asr_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_asr_2eproto;
class State;
struct StateDefaultTypeInternal;
extern StateDefaultTypeInternal _State_default_instance_;
class Unit;
struct UnitDefaultTypeInternal;
extern UnitDefaultTypeInternal _Unit_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::State* Arena::CreateMaybeMessage<::State>(Arena*);
template<> ::Unit* Arena::CreateMaybeMessage<::Unit>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Unit final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Unit) */ {
 public:
  inline Unit() : Unit(nullptr) {}
  ~Unit() override;
  explicit PROTOBUF_CONSTEXPR Unit(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Unit(const Unit& from);
  Unit(Unit&& from) noexcept
    : Unit() {
    *this = ::std::move(from);
  }

  inline Unit& operator=(const Unit& from) {
    CopyFrom(from);
    return *this;
  }
  inline Unit& operator=(Unit&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Unit& default_instance() {
    return *internal_default_instance();
  }
  static inline const Unit* internal_default_instance() {
    return reinterpret_cast<const Unit*>(
               &_Unit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Unit& a, Unit& b) {
    a.Swap(&b);
  }
  inline void Swap(Unit* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Unit* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Unit* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Unit>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Unit& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Unit& from) {
    Unit::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Unit* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Unit";
  }
  protected:
  explicit Unit(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActionsIdFieldNumber = 2,
    kUnitIdFieldNumber = 1,
  };
  // repeated int32 actions_id = 2;
  int actions_id_size() const;
  private:
  int _internal_actions_id_size() const;
  public:
  void clear_actions_id();
  private:
  int32_t _internal_actions_id(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_actions_id() const;
  void _internal_add_actions_id(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_actions_id();
  public:
  int32_t actions_id(int index) const;
  void set_actions_id(int index, int32_t value);
  void add_actions_id(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      actions_id() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_actions_id();

  // int32 unit_id = 1;
  void clear_unit_id();
  int32_t unit_id() const;
  void set_unit_id(int32_t value);
  private:
  int32_t _internal_unit_id() const;
  void _internal_set_unit_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Unit)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > actions_id_;
    mutable std::atomic<int> _actions_id_cached_byte_size_;
    int32_t unit_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_asr_2eproto;
};
// -------------------------------------------------------------------

class State final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:State) */ {
 public:
  inline State() : State(nullptr) {}
  ~State() override;
  explicit PROTOBUF_CONSTEXPR State(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  State(const State& from);
  State(State&& from) noexcept
    : State() {
    *this = ::std::move(from);
  }

  inline State& operator=(const State& from) {
    CopyFrom(from);
    return *this;
  }
  inline State& operator=(State&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const State& default_instance() {
    return *internal_default_instance();
  }
  static inline const State* internal_default_instance() {
    return reinterpret_cast<const State*>(
               &_State_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(State& a, State& b) {
    a.Swap(&b);
  }
  inline void Swap(State* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(State* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  State* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<State>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const State& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const State& from) {
    State::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(State* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "State";
  }
  protected:
  explicit State(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnitsFieldNumber = 1,
    kFindSolutionFieldNumber = 2,
  };
  // repeated .Unit units = 1;
  int units_size() const;
  private:
  int _internal_units_size() const;
  public:
  void clear_units();
  ::Unit* mutable_units(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Unit >*
      mutable_units();
  private:
  const ::Unit& _internal_units(int index) const;
  ::Unit* _internal_add_units();
  public:
  const ::Unit& units(int index) const;
  ::Unit* add_units();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Unit >&
      units() const;

  // optional bool find_solution = 2;
  bool has_find_solution() const;
  private:
  bool _internal_has_find_solution() const;
  public:
  void clear_find_solution();
  bool find_solution() const;
  void set_find_solution(bool value);
  private:
  bool _internal_find_solution() const;
  void _internal_set_find_solution(bool value);
  public:

  // @@protoc_insertion_point(class_scope:State)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Unit > units_;
    bool find_solution_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_asr_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Unit

// int32 unit_id = 1;
inline void Unit::clear_unit_id() {
  _impl_.unit_id_ = 0;
}
inline int32_t Unit::_internal_unit_id() const {
  return _impl_.unit_id_;
}
inline int32_t Unit::unit_id() const {
  // @@protoc_insertion_point(field_get:Unit.unit_id)
  return _internal_unit_id();
}
inline void Unit::_internal_set_unit_id(int32_t value) {
  
  _impl_.unit_id_ = value;
}
inline void Unit::set_unit_id(int32_t value) {
  _internal_set_unit_id(value);
  // @@protoc_insertion_point(field_set:Unit.unit_id)
}

// repeated int32 actions_id = 2;
inline int Unit::_internal_actions_id_size() const {
  return _impl_.actions_id_.size();
}
inline int Unit::actions_id_size() const {
  return _internal_actions_id_size();
}
inline void Unit::clear_actions_id() {
  _impl_.actions_id_.Clear();
}
inline int32_t Unit::_internal_actions_id(int index) const {
  return _impl_.actions_id_.Get(index);
}
inline int32_t Unit::actions_id(int index) const {
  // @@protoc_insertion_point(field_get:Unit.actions_id)
  return _internal_actions_id(index);
}
inline void Unit::set_actions_id(int index, int32_t value) {
  _impl_.actions_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:Unit.actions_id)
}
inline void Unit::_internal_add_actions_id(int32_t value) {
  _impl_.actions_id_.Add(value);
}
inline void Unit::add_actions_id(int32_t value) {
  _internal_add_actions_id(value);
  // @@protoc_insertion_point(field_add:Unit.actions_id)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Unit::_internal_actions_id() const {
  return _impl_.actions_id_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Unit::actions_id() const {
  // @@protoc_insertion_point(field_list:Unit.actions_id)
  return _internal_actions_id();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Unit::_internal_mutable_actions_id() {
  return &_impl_.actions_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Unit::mutable_actions_id() {
  // @@protoc_insertion_point(field_mutable_list:Unit.actions_id)
  return _internal_mutable_actions_id();
}

// -------------------------------------------------------------------

// State

// repeated .Unit units = 1;
inline int State::_internal_units_size() const {
  return _impl_.units_.size();
}
inline int State::units_size() const {
  return _internal_units_size();
}
inline void State::clear_units() {
  _impl_.units_.Clear();
}
inline ::Unit* State::mutable_units(int index) {
  // @@protoc_insertion_point(field_mutable:State.units)
  return _impl_.units_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Unit >*
State::mutable_units() {
  // @@protoc_insertion_point(field_mutable_list:State.units)
  return &_impl_.units_;
}
inline const ::Unit& State::_internal_units(int index) const {
  return _impl_.units_.Get(index);
}
inline const ::Unit& State::units(int index) const {
  // @@protoc_insertion_point(field_get:State.units)
  return _internal_units(index);
}
inline ::Unit* State::_internal_add_units() {
  return _impl_.units_.Add();
}
inline ::Unit* State::add_units() {
  ::Unit* _add = _internal_add_units();
  // @@protoc_insertion_point(field_add:State.units)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Unit >&
State::units() const {
  // @@protoc_insertion_point(field_list:State.units)
  return _impl_.units_;
}

// optional bool find_solution = 2;
inline bool State::_internal_has_find_solution() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool State::has_find_solution() const {
  return _internal_has_find_solution();
}
inline void State::clear_find_solution() {
  _impl_.find_solution_ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool State::_internal_find_solution() const {
  return _impl_.find_solution_;
}
inline bool State::find_solution() const {
  // @@protoc_insertion_point(field_get:State.find_solution)
  return _internal_find_solution();
}
inline void State::_internal_set_find_solution(bool value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.find_solution_ = value;
}
inline void State::set_find_solution(bool value) {
  _internal_set_find_solution(value);
  // @@protoc_insertion_point(field_set:State.find_solution)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_asr_2eproto
