# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\"\x1a\n\x04Unit\x12\x12\n\nactions_id\x18\x01 \x03(\x05\"\x1d\n\x05State\x12\x14\n\x05units\x18\x01 \x03(\x0b\x32\x05.Unitb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNIT._serialized_start=13
  _UNIT._serialized_end=39
  _STATE._serialized_start=41
  _STATE._serialized_end=70
# @@protoc_insertion_point(module_scope)
